greeting: Hello, ${name}.

app:
  tabs:
    # Neither of these works in the code.
    # defaultActiveKey: ${$$.summary.tab}
    defaultActiveKey: Summary

mainSelectors:
  prologue: I am interested in information about projected climate change ...
  seasonPrefix: for a typical
  regionPrefix: in
  periodPrefix: during the

summary:
  tab: Summary
  title: "## Summary of Climate Change for ${region} in the ${futureTimePeriod}"
  # It's tempting to do this content as a Markdown table, but unfortunately
  # MD doesn't# let you span table rows or columns.
  table:
    heading:
      variable: Climate Variable
      season: Season
      projectedChange: Projected Change from ${$$.fragments.period} Baseline
      ensembleMedian: Ensemble Median
      range: Range (10th to 90th percentile)
    rows:
      variable: |
        ${variable.label}${variable.derived ? '*': ''} (${variable.units})
      season: ${season.label}
      ensembleMedian: ${format(season.ensembleMedian)}${units}
      range: |
        ${format(season.range.min)}${isLong(units) ? '': units} to
        ${format(season.range.max)}${units}
    contents:
      - variable: tasmean
        seasons:
          - annual
      - variable: pr
        seasons:
          - annual
          - summer
          - winter
      - variable: prsn
        seasons:
          - winter
          - spring
# TODO: Uncomment when stats backend complete
#      - variable: gdd
#        seasons:
#          - annual
#      - variable: hdd
#        seasons:
#          - annual
#      - variable: fdETCCDI
#        seasons:
#          - annual
  notes:
    general: |
      The table above shows projected changes in average (mean) temperature,
      precipitation and several derived climate variables from the
      baseline historical period
      (${baselineDecade}s)
      to the ${futureDecade}s
      for the ${region} region.
      The ensemble median is a mid-point value, chosen from a PCIC standard
      set of Global Climate Model (GCM) projections (see the 'Notes' tab for
      more information).
      The range values represent the lowest and highest results within the set.

      Please note that this summary table does not depend on the choice of season
       (*${$$.mainSelectors.seasonPrefix}...*) made at the left.
       However, that setting does affect results on the other tabs.
    derivedVars: |
      &ast; These values are derived from temperature and precipitation.
      Please select the appropriate variable tab for more information.

impacts:
  tab: Impacts
  title: "## Potential Impacts for ${region} in the ${futureTimePeriod}"
  prologue: |
    Below, you can view a list of potential impacts that may affect ${region}
    in the ${futureDecade}s.
    This is intended to provide a starting point for more detailed local
    assessment of climate change impacts.
    These are based on limited climate change information, as shown in the
    detailed rules logic.
    These rules were developed based on a workshop attended by climate
    impacts experts and subsequent peer review.
    Although quite comprehensive, the rules are a work in progress, and some
    key impacts or management implications may be missing.
    We welcome contributions and suggestions from users of Plan2Adapt.
  rulesLogic:
    prologue: |
      The table below shows all of the rules used to determine whether to
      display specific impacts and specific management implications in the
      Impacts tab. This preliminary compilation of rules was developed based
      on a workshop attended by climate impacts experts and subsequent peer
      review. They are fairly technical and quite a bit of shorthand is used,
      as described under terminology below. Although quite comprehensive,
      the rules are a work in progress, and some key impacts or management
      implications may be missing. We welcome contributions and suggestions
      from users of Plan2Adapt.

      There are two types of rules: internal rules and impacts rules.
      The internal rules, listed first below, are used as part of the
      conditions in many other rules, with additional information given
      under the management implications column. The internal rule "snow",
      for example, is true if a region has locations with hydrological regimes
      that would be classified as snowfall-dominated based on the 1961-1990
      climatology. This is determined by the condition of whether any
      50km cells within the selected region have mean winter temperatures
      below -6°C. The "hybrid" and "rain" rules are similar but for hybrid
      and rain-dominated classifications. Note that a region may have
      locations that meet multiple classifications.
      The "future-..." internal rules make the same determination about the
      region in the selected future time period.

      The impacts rules display information directly in the Potential Impacts
      table, and are also sometimes used as part of conditions for other rules.
      Their IDs are classified by sector: For example, "2a-iv-bio", which
      comes under the general impact of Reduced Water Supply, has management
      implications that appear under the Biodiversity sector.
      The rule, which is about the effect of a decrease in moisture
      availability on habitat, displays based on the condition that at least
      one season has a decrease in precipitation according to at least 75%
      of the climate model projections (strong agreement) is met.

      ### Notation

      | Item | Meaning |
      | - | - |
      | s0p/s50p/s100p | Spatial minimum/median/maximum 0.5° grid box value in the region. |
      | iastddev | Interannual standard deviation of the monthly, seasonal, or annual mean. |
      | hist | CRU TS 2.1 1961-1990 historical baseline. |
      | e25p/e75p | GCM ensemble 25th/75th percentile. This is always an interannual mean. |
      | ann, djf, mam, jja, son | Annual, Dec/Jan/Feb, Mar/Apr/May, Jun/Jul/Aug, Sep/Oct/Nov. |
      | anom | Value is an anomaly (not a percentage) from the baseline (i.e. future minus historical). |
      | percent | Value is a percentage anomaly from the baseline. |
      | rule_<rule-ID> | A reference to another rule. |
      | region_oncoast | Whether the region is on the coast. |
      | rule ? if_true : if_false | Checks whether a rule is true; if true, runs the clause represented by if_true; if false, runs the clause represented by if_false. |

      ### Variables
      
      | Variable | Description | Units |
      | - | - | - |
      | temp | Mean Temperature | °C |
      | prec | Total precipitation | mm/day |
      | pass | Snowfall | mm snow water equivalent |
      | dg05 | Growing DD (Degree-Days Above 5°C) | degree-days |
      | dl18 | Heating DD (Degree-Days Below 18°C) | degree-days |
      | nffd | Number of Frost-Free Days | days |

      If not otherwise specified, values are an interannual and spatial mean,
      and in the same units used on the maps (°C for temperatures, mm per day
      for precipitation, etc.).

      ### Rules

      Given a set of projected climate data (determined by the period, region,
      and time period you have selected), each rule evaluates to either true
      or false. If the rule is true, then that means the effect it signals
      is likely to occur in that scenario, and we say the rule is active.
      The effects signalled by active rules are summarized for easy
      interpretation in the By Category and By Sector tabs.

      In the table below, active rules have a white background;
      inactive rules have a grey background.

    table:
      showInactiveRulesButton:
        true: Hide Inactive Rules
        false: Show Inactive Rules
      heading:
        ruleId: Rule ID
        condition: Condition
        category: Category
        sector: Sector
        effects: Effects
        notes: Management Implications

maps:
  tab: Maps
  title: "## ${season} ${variable} for ${region}"
  historical:
    title: "### Historical: ${$$.fragments.period}"
  projected:
    title: "### Projected: ${$$.fragments.period}"
  displaySpec:
    fallback:
      palette: seq-Oranges
      range:
        min: -50
        max: 50
      ticks: [-50, 0, 50]
    gdd:
      palette: seq-Oranges
      range:
        min: 0
        max: 4000
      ticks: [0, 1000, 2000, 3000, 4000]
    hdd:
      palette: seq-Oranges
      range:
        min: 0
        max: 10000
      ticks: [0, 2000, 4000, 6000, 8000, 10000]
    pr:
      palette: seq-Greens
      range:
        min: 0
        max: 20
      ticks: [0, 5, 10, 15, 20]
    tasmax:
      palette: div-BuRd
      range:
        min: -30
        max: 40
      ticks: [-30, -20, -10, 0, 10, 20, 30, 40]
    tasmin:
      palette: div-BuRd
      range:
        min: -40
        max: 30
      ticks: [-40, -30, -20, -10, 0, 10, 20, 30]

graph:
  tab: Graph
  title: "## Range of projected change in ${season} ${variable} for ${region}"

notes:
  tab: Notes
  content: |
    ## Notes

    1. Multiple projections information is drawn from a set of 30 GCM
    projections based on results from 15 different Global Climate Models (GCMs),
    each using one run of a high (A2) and a lower (B1) greenhouse gas emissions
    scenario. By the end of the 21st century, these scenarios anticipate an atmospheric concentration of greenhouse gases of approximately 1250 ppm (A2) and 600 ppm (B1), expressed as carbon dioxide (CO2) equivalent. Neither scenario incorporates the effects of international agreements on the reduction of greenhouse gas emissions, though other socio-economic factors like population growth are modelled. Each GCM comes from a different modelling centre (e.g. the Hadley Centre (UK), National Centre for Atmospheric Research (USA), Geophysical Fluid Dynamics Laboratory (USA), and Commonwealth Scientific and Industrial Research Organisation (Australia), etc.).

    1. The single projection used for the maps is the CGCM3 A2 run 4.
    CGCM3 is the Canadian Global Climate Model, developed and run by
    Environment Canada's Canadian Centre for Climate Modelling and Analysis
    at the University of Victoria. The A2 specification denotes a possible
    future where emissions continue to rise alongside increases in human
    population and economic growth. A2 is one emissions scenario amongst
    several developed by the Intergovernmental Panel on Climate Change (IPCC)
    and published in its Special Report on Emissions Scenarios (SRES)
    (see 'References' tab).

    1. High-resolution climate data is obtained by using the ClimateBC
    empirical downscaling tool. ClimateBC uses interpolation, an elevation
    correction on temperature, and the PRISM (Parameter-elevation Regressions
    on Independent Slopes Model) 4 km high-resolution climatology derived
    from a multiple regression of weather station data against topographical
    features. This projected change from Global Climate Models (GCMs) is
    applied to the high resolution past in order to obtain an estimate of
    future climate at the same high resolution.

    1. The 2020s, 2050s, and 2080s time periods are meant to be used as three
    representative planning horizons over the 21st century. Results for these
    three planning horizons are computed by averaging GCM projections over
    the 2010-2039, 2040-2069, and 2070-2099 periods, respectively.

    1. With the exception of temperature and precipitation, most variable
    values shown here are not directly observed or obtained from the GCMs.
    Instead, they are derived from temperature and/or precipitation using
    methods described in Wang et al., 2006 (see 'References' tab).

    ## Acknowledgements

    Development of this tool has been made possible through funding and
    support provided by the BC Ministry of Environment and the
    BC Ministry of Forests and Range Forest Science Program and is a
    project of Natural Resources Canada's British Columbia Regional
    Adaptation Collaborative.

references:
  tab: References
  content: |
    British Columbia Ministry of Water, Land and Air Protection. 2002. _Indicators of Climate Change for British Columbia 2002_. Victoria, BC. 48 pp.

    Bronaugh, D., T. Murdock. In review. _Developing Improved Degree-Day Regressions_. Pacific Climate Impacts Consortium report; 33 pp.

    Cohen, Stewart. 2009. _Climate Change in the 21st Century - Understanding the World's Biggest Crisis_. McGill-Queen's University Press. 379 pp.

    Daly, C., W.P. Gibson, G.H. Taylor, G.L. Johnson, and P. Pasteris. 2002. "A knowledge-based approach to the statistical mapping of climate", _Climate Research_, 22: 99-113. Details the PRISM 4km climatology.

    Hamlet A.F., D.P. Lettenmaier. 2005. _Effects of Temperature and Precipitation Variability on Snowpack Trends in the Western U.S._ Journal of Climate, 18 (21): pp. 4545-4561.

    Hamlet A.F., D.P. Lettenmaier. 2007. _Effects of 20th Century Warming and Climate Variability on Flood Risk in the Western U.S._ Water Resources Research, 43: W06427.doi:10.1029/2006WR005099.

    Intergovernmental Panel on Climate Change. 2000. _Special Report on Emissions Scenarios_. Cambridge University Press. 570 pp. http://www.ipcc.ch/ipccreports/sres/emission/index.htm

    Mote P.W., A.F. Hamlet, M. Clark, D.P. Lettenmaier. 2005. _Declining Mountain Snowpack in Western North America_. Bulletin of the American Meteorological Society, 86(1):39-49.

    Murdock, T.Q. and D.L. Spittlehouse. 2011. _Selecting and Using Climate Change Scenarios for British Columbia_. Pacific Climate Impacts Consortium, University of Victoria, Victoria, BC, 39 pp.

    Rodenhuis, D.R., Bennett, K.E., Werner, A.T., Murdock, T.Q., Bronaugh, D. Revised 2009. _Hydro-climatology and future climate impacts in British Columbia_. Pacific Climate Impacts Consortium, University of Victoria, Victoria BC, 132 pp. Provides additional information on future climate projects in British Columbia.

    Wang, T.L., Hamann, A., Spittlehouse, D.L. and Aitken, S.N., 2006. "Development of scale-free climate data for Western Canada for use in resource management", _International Journal of Climatology_, 26: 383-397. Details the ClimateBC empirical downscaling tool.

fragments:
  period: ${start_date}-${end_date}
  variablePrefix: Show details about
