# This docker-compose uses the following shell environment variables:
#
# `SDP_TAG`: Image tag
# `SDP_PORT`: External port to map to
#
# Their values are set appropriately in the Makefile for use on a workstation.
# For use in a production setting, either set the shell
# variables appropriately when invoking docker-compose, or modify (a copy of)
# this file with the desired values.

version: "3.8"
services:
  plan2adapt-v2-frontend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: pcic/plan2adapt-v2-frontend:${SDP_TAG}
    container_name: plan2adapt-v2-frontend
    ports:
      - "${SDP_PORT}:8080"
    volumes:
      - type: bind
        source: /storage/data/projects/comp_support/plan2adapt-v2/external-text.yaml
        target: /app/public/external-text/default.yaml
        read_only: true
      - ./config.js:/app/config.js
