name: CI Tests

on: push

jobs:
  node-test:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js 9.x
      uses: actions/setup-node@v1
      with:
        node-version: 9.x
    - name: Node.js Test Suite
      run: |
        npm install
        npm test
