name: Docker Publishing

on:
  push:
    branches:
      - '*'
  release:
    type:
      - created

jobs:
  docker-publish:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
      - name: Export REACT_APP_VERSION env var
        run: |
          git fetch --prune --unshallow
          echo ::set-env name=REACT_APP_VERSION::"$(git describe --tags --abbrev=0) ($(git rev-parse --abbrev-ref HEAD):$(git log -1 --format=%h))"
      - name: Publish to Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.pcicdevops_at_dockerhub_username }}
          password: ${{ secrets.pcicdevops_at_dockerhub_password }}
          repository: pcic/plan2adapt-v2-frontend
          tag_with_ref: true
          build_args: REACT_APP_VERSION=${{ env.REACT_APP_VERSION }}
