name: Docker Image Scan

on:
  push:
    branches:
      - master
      - '*security*'

jobs:
  anchore:

    runs-on: ubuntu-18.04

    steps:
      - name: Wait for image to be published
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: publish
          ref: ${{ github.sha }}
      - name: Get branch name
        uses: nelonoel/branch-name@v1
      - name: Set Branch Name to Environment Variable
        run: echo ::set-env name=TAG::$(echo ${BRANCH_NAME})
      - name: Scan Image
        uses: anchore/scan-action@master
        with:
          image-reference: "pcic/plan2adapt-v2-frontend:${{ env.TAG }}"
          fail-build: true
        if: steps.wait-for-build.outputs.conclusion == 'success'
