name: Node CI

on: push

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@master
    - name: Set up Node.js 14.21.3
      uses: actions/setup-node@v1
      with:
        node-version: 14.21.3
    - name: Node.js Test Suite
      run: |
        npm install
        npm test
